CREATE DATABASE COCINA;
USE COCINA;

CREATE TABLE RECETAS(
	COD INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(200),
    ENTREGA MEDIUMTEXT,
    ELABORACION LONGTEXT,
    IMAG1 VARCHAR(200),
    IMAG2 VARCHAR(200),
    DIFICULTAD SET('BAJA','MEDIA','ALTA'),
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    COMENSALES INTEGER
);

SELECT * FROM RECETAS;