/* EQUIPOS CUYO NOMBRE COMIENZA POR H Y TERMINA POR S */
SELECT * FROM EQUIPOS WHERE NOMBRE LIKE 'H%S';

/* NÚMERO DE EQUIPOS QUE HAY EN CADA CONFERENCIA */
SELECT CONFERENCIA, COUNT(*) FROM EQUIPOS GROUP BY CONFERENCIA;

/* JUGADORES QUE PESAN MÁS DE 100 KG Y MIDEN MAS DE 182 */
SELECT CODIGO, NOMBRE, PROCEDENCIA, ROUND(((100 * ((0.453592 * REPLACE(ALTURA, '-', ',')) / 1)) / 1), 2) AS ALTURA, ROUND(((0.3048 * PESO) / 1), 2) AS PESO, POSICION, NOMBRE_EQUIPO
  FROM JUGADORES
 WHERE ROUND(((100 * ((0.453592 * REPLACE(ALTURA, '-', ',')) / 1)) / 1), 2) > 182
	   AND ROUND(((0.3048 * PESO) / 1), 2) > 100;

/* JUGADORES CUYO 3ª LETRA DEL NOMBRE ES V */
SELECT * FROM JUGADORES WHERE SUBSTRING(NOMBRE, 1, 3) LIKE '%V';

/* JUGADORES ARGENTINOS, ESPAÑOLES Y FRANCESES POR CADA EQUIPO */
SELECT * FROM JUGADORES WHERE (PROCEDENCIA = "SPAIN" OR PROCEDENCIA = "ARGENTINA" OR PROCEDENCIA = "FRANCE") ORDER BY NOMBRE_EQUIPO ASC;

/* CUANTAS NACIONALIDADES DE PROCEDENCIA DIFERENTES HAY EN LA TABLA JUGADORES */
SELECT PROCEDENCIA, COUNT(*) FROM JUGADORES GROUP BY PROCEDENCIA;

/* CUAL ES LA MÁXIMA ALTURA DE UN JUGADOR Y LA MINIMA , TAMBIÉN EL PESO MÁXIMO Y EL MINIMO */
SELECT MIN(ALTURA) AS ALTURA_MINIMA, MIN(PESO) AS PESO_MINIMO, MAX(ALTURA) AS ALTURA_MAXIMA, MAX(PESO) AS PESO_MAXIMO
  FROM JUGADORES;

/* CUAL ES LA MEDIA DE ALTURA POR EQUIPO DE LOS JUGADORES QUE LOS COMPONEN */
SELECT NOMBRE_EQUIPO, round(AVG(ALTURA), 2) AS ALTURA_MEDIA FROM JUGADORES GROUP BY NOMBRE_EQUIPO;

/* CUANTO PESAN DE MEDIA LOS JUGADORES DE DE CADA EQUIPO */
SELECT NOMBRE_EQUIPO, round(AVG(PESO), 2) AS PESO_MEDIO FROM JUGADORES GROUP BY NOMBRE_EQUIPO;

/* CUANTO PESAN DE MEDIA  LOS JUGADORES ESPAÑOLES FRENTE AL RESTO DE TODOS LOS JUGADORES */
SELECT PROCEDENCIA, round(AVG(PESO), 2) AS PESO_MEDIO FROM JUGADORES GROUP BY PROCEDENCIA HAVING PROCEDENCIA = "SPAIN";