CREATE DATABASE JARDINERIA;

USE JARDINERIA;

SELECT * FROM EMPLEADO;

SELECT CODIGO_EMPLEADO, NOMBRE, APELLIDO1, APELLIDO2, EXTENSION, EMAIL, PUESTO FROM EMPLEADO;

SELECT CODIGO_EMPLEADO, NOMBRE, APELLIDO1, APELLIDO2, EXTENSION, EMAIL, PUESTO 
  FROM EMPLEADO
  INTO OUTFILE 'C:/Users/mario/OneDrive/DAM/Bases de datos/Ejemplos BDD/empleados.csv'
  FIELDS TERMINATED BY ';'
  LINES TERMINATED BY '\n';

CREATE DATABASE COPYJAR;

USE COPYJAR;

CREATE TABLE IF NOT EXISTS EMPLEADOS(
	CODIGO INTEGER,
    NOMBRE VARCHAR(50),
    APEL1 VARCHAR(50),
    APEL2 VARCHAR(50),
    EXT VARCHAR(4),
    MAIL VARCHAR(50),
    CARGO VARCHAR(50)
);

LOAD DATA INFILE 'C:/Users/mario/OneDrive/DAM/Bases de datos/Ejemplos BDD/empleados.csv' 
      INTO TABLE EMPLEADOS
      FIELDS TERMINATED BY ';'
      LINES TERMINATED BY '\n'