CREATE DATABASE EMPRESA;
USE EMPRESA;

CREATE TABLE IF NOT EXISTS PROVEEDORES(
	CODPRO INTEGER COMMENT 'CLAVE INTERNA DEL PROVEEDOR',
    NOM VARCHAR(100) NOT NULL COMMENT 'NOMBRE DEL PROVEEDOR',
    DIR VARCHAR(200) COMMENT 'DORECCION DEL PROVEEDOR',
    TEL VARCHAR(12) NOT NULL COMMENT 'TELEFONO DEL PROVEEDOR',
    EMAIL VARCHAR(100) NOT NULL COMMENT 'CORREO DEL PROVEEDOR',
    CRED NUMERIC COMMENT 'CREDITO'
);

LOAD DATA INFILE 'C:/Users/mario/OneDrive/DAM/Bases de datos/Ejemplos BDD/ficheroraro.txt'
		  INTO TABLE PROVEEDORES
          FIELDS TERMINATED BY ','
          LINES TERMINATED BY '**'
          STARTING BY '---'
          IGNORE 1 LINES;

SELECT * FROM PROVEEDORES;

TRUNCATE PROVEEDORES;

CREATE TABLE IF NOT EXISTS PRUEBA(
	CODPRO INTEGER AUTO_INCREMENT COMMENT 'CLAVE INTERNA DEL PROVEEDOR',
    NOM VARCHAR(100) NOT NULL COMMENT 'NOMBRE DEL PROVEEDOR',
    DIR VARCHAR(200) COMMENT 'DORECCION DEL PROVEEDOR',
    TEL VARCHAR(12) NOT NULL COMMENT 'TELEFONO DEL PROVEEDOR',
    EMAIL VARCHAR(100) NOT NULL COMMENT 'CORREO DEL PROVEEDOR',
    CRED NUMERIC COMMENT 'CREDITO',
    PRIMARY KEY (CODPRO)
);

LOAD DATA INFILE 'C:/Users/mario/OneDrive/DAM/Bases de datos/Ejemplos BDD/ficheroraro.txt'
		  INTO TABLE PRUEBA
          FIELDS TERMINATED BY ','
          LINES TERMINATED BY '**'
          STARTING BY '---'
          IGNORE 1 LINES;

INSERT INTO PRUEBA (NOM, DIR, TEL, EMAIL, CRED) VALUES ('ADURA, VERG', 'FUCKING, ALEMANIA', '123456789', 'POLL@ADU.RA', '1294293');

SELECT * FROM PRUEBA;

DELETE FROM PRUEBA WHERE CODPRO = 2;
DELETE FROM PRUEBA WHERE CODPRO = 4;
DELETE FROM PRUEBA WHERE CODPRO = 1;
DELETE FROM PRUEBA WHERE CODPRO = 3;
DELETE FROM PRUEBA WHERE CODPRO = 5;
DELETE FROM PRUEBA;

TRUNCATE PRUEBA;

SELECT CONCAT_WS(',', CODPRO, NOM, DIR, TEL, EMAIL, CRED) AS DATOS FROM PRUEBA;

INSERT INTO PROVEEDORES SELECT * FROM PRUEBA;

UPDATE PRUEBA SET CRED = 10 WHERE CODPRO = 1;

UPDATE PRUEBA SET CRED = ((SELECT CRED FROM PRUEBA WHERE CODPRO = 1) + 500) WHERE CODPRO = 1;

ALTER TABLE PRUEBA ADD CREFIN INTEGER COMMENT 'CREDITO FINAL';

UPDATE PRUEBA SET CREFIN = 100;

SET SQL_SAFE_UPDATES = 0;

UPDATE PRUEBA SET CREFIN = CREFIN * 1.35;

ALTER TABLE PRUEBA MODIFY CREFIN DOUBLE COMMENT 'CREDITO FINAL';