CREATE DATABASE NBA;
USE NBA;

SELECT * FROM JUGADORES;
SELECT * FROM JUGADORES WHERE PROCEDENCIA = 'SPAIN';
SELECT * FROM JUGADORES WHERE NOMBRE LIKE '%GAS%';
SELECT * FROM EQUIPOS WHERE NOMBRE LIKE 'C%';
SELECT NOMBRE_EQUIPO, COUNT(*) AS NUMERO_JUGADORES FROM JUGADORES GROUP BY NOMBRE_EQUIPO;
SELECT NOMBRE_EQUIPO, COUNT(*) AS NUMERO_JUGADORES FROM JUGADORES WHERE NOMBRE_EQUIPO LIKE 'C%' GROUP BY NOMBRE_EQUIPO;
SELECT NOMBRE_EQUIPO, COUNT(*) AS NUMERO_JUGADORES FROM JUGADORES GROUP BY NOMBRE_EQUIPO HAVING NUMERO_JUGADORES > 15;
SELECT * FROM JUGADORES WHERE (POSICION = 'F' OR POSICION = 'F-G') AND PESO > 190;
SELECT NOMBRE_EQUIPO, NOMBRE, POSICION, PESO FROM JUGADORES WHERE POSICION LIKE '%f%' AND PESO >= 190;

CREATE DATABASE NBA_BACK;
USE NBA_BACK;

CREATE TABLE JUGADORES SELECT * FROM NBA.JUGADORES;

SELECT * FROM JUGADORES;
SELECT CODIGO, NOMBRE, PROCEDENCIA, ROUND(((100 * ((0.453592 * REPLACE(ALTURA, '-', ',')) / 1)) / 1), 2) AS ALTURA, ROUND(((0.3048 * PESO) / 1), 2) AS PESO, POSICION, NOMBRE_EQUIPO FROM JUGADORES;

SET SQL_SAFE_UPDATES = 0;

UPDATE JUGADORES SET ALTURA = ROUND(((100 * ((0.453592 * REPLACE(ALTURA, '-', ',')) / 1)) / 1), 2), PESO = ROUND(((0.3048 * PESO) / 1), 2);

SELECT * FROM EQUIPOS