CREATE DATABASE CHAMPIONFORCE;
USE CHAMPIONFORCE;

CREATE TABLE IF NOT EXISTS CAMPEONATO(
	CODCAMP INTEGER AUTO_INCREMENT PRIMARY KEY COMMENT 'CODIGO INTERNO DEL CAMPEONATO',
    DENOM VARCHAR(100) NOT NULL COMMENT 'NOMBRE DEL CAMPEONATO',
    LUGAR VARCHAR(50) NOT NULL COMMENT 'LUGAR DEL CAMPEONATO',
    CATE VARCHAR(80) NOT NULL COMMENT 'CATEGORIA DEL CAMPEONATO',
    FASE INTEGER NOT NULL COMMENT 'FASES DEL CAMPEONATO',
    FCHINI DATE NOT NULL COMMENT 'FECHA DE INICIO DEL CAMPEONATO',
    FCHFIN DATE NOT NULL COMMENT 'FECHA DE FIN DEL CAMPEONATO'
);

CREATE TABLE IF NOT EXISTS ARBITROS(
	CODARB INTEGER AUTO_INCREMENT PRIMARY KEY COMMENT 'CODIGO INTERNO DEL ARBITRO',
    NOM VARCHAR(80) NOT NULL COMMENT 'NOMBRE DEL ARBITRO',
    NACIO VARCHAR(20) NOT NULL COMMENT 'NACIONALIDAD DEL ARBITRO',
    AMBITO VARCHAR(20) NOT NULL COMMENT 'AMBITO EN EL QUE TRABAJA EL ARBITRO',
    FCHNACI DATE NOT NULL COMMENT 'FECHA DE NACIMIENTO DEL ARBITRO'
);

CREATE TABLE IF NOT EXISTS EQUIPO(
	CODEQ INTEGER AUTO_INCREMENT PRIMARY KEY COMMENT 'CODIGO INTERNO DEL EQUIPO',
    NOMEQ VARCHAR(100) NOT NULL COMMENT 'NOMBRE DEL EQUIPO',
    ESCUDO VARCHAR(100) COMMENT 'LINK DE LA IMAGEN DEL ESCUDO',
    ESTADIO INTEGER NOT NULL COMMENT 'ESTADIO AL QUE PERTENECE EL EQUIPO',
    FCHFUND DATE NOT NULL COMMENT 'FECHA DE FUNDACIÓN DEL EQUIPO',
    CIUDAD VARCHAR(20) NOT NULL COMMENT 'CIUDAD AL QUE PERTENECE EL EQUIPO',
    HIMNO longtext NOT NULL COMMENT 'HIMNO DEL EQUIPO',
    CONSTRAINT REL_ESTADIO_EQUIPO FOREIGN KEY (ESTADIO) REFERENCES ESTADIOS (CODES)
);

CREATE TABLE IF NOT EXISTS ESTADIOS(
	CODES INTEGER AUTO_INCREMENT PRIMARY KEY COMMENT 'CODIGO INTERNO DEL ESTADIO',
    NOM VARCHAR(100) NOT NULL COMMENT 'NOMBRE DEL ESTADIO',
    CIU VARCHAR(20) NOT NULL COMMENT 'CIUDAD EN LA QUE SE SITUA EL ESTADIO',
    PAIS VARCHAR(20) NOT NULL COMMENT 'PAIS EN EL QUE SE SITUA EL ESTADIO',
    AFO INTEGER NOT NULL COMMENT 'AFORO MAXIMO QUE SOPORTA EL ESTADIO'
);

CREATE TABLE IF NOT EXISTS JUGADORES(
	CODJU INTEGER AUTO_INCREMENT PRIMARY KEY COMMENT 'CODIGO INTERNO DEL JUGADOR',
    NOM VARCHAR(80) NOT NULL COMMENT 'NOMBRE DEL JUGADOR',
    FCHNACI DATE NOT NULL COMMENT 'FECHA DE NACIMIENTO DEL JUGADOR',
    NAC VARCHAR(20) NOT NULL COMMENT 'NACIONALIDAD DEL JUGADOR',
    CIU VARCHAR(20) NOT NULL COMMENT 'CIUDAD DE NACIMIENTO DEL JUGADOR'
);

CREATE TABLE IF NOT EXISTS PLANTILLA(
	CODEQ INTEGER NOT NULL COMMENT 'CODIGO INTERNO DEL EQUIPO',
    CODJU INTEGER NOT NULL COMMENT 'CODIGO INTERNO DEL JUGADOR',
    FCHINI DATE NOT NULL COMMENT 'FECHA DE INICIO DEL FICHAJE',
    FCHFIN DATE NOT NULL COMMENT 'FECHA DE FIN DEL FICHAJE',
    SAL INTEGER NOT NULL COMMENT 'SALARIO BRUTO ANUAL DEL JUGADOR',
    CLARES INTEGER NOT NULL COMMENT 'CLAUSULA DE RESCISION DEL CONTRATO',
    
    CONSTRAINT REL_CODEQ FOREIGN KEY (CODEQ) REFERENCES EQUIPO (CODEQ),
    CONSTRAINT REL_CODJU FOREIGN KEY (CODJU) REFERENCES JUGADORES (CODJU)
);

CREATE TABLE IF NOT EXISTS PLANTILLA(
	CODCAMP INTEGER NOT NULL COMMENT 'CODIGO INTERNO DEL CAMPEONATO',
    CODES INTEGER NOT NULL COMMENT 'CODIGO INTERNO DEL ESTADIO',
	CODARB INTEGER NOT NULL COMMENT 'CODIGO INTERNO DEL ARBITRO',
    EQUILOC INTEGER NOT NULL COMMENT 'CODIGO INTERNO DEL EQUIPO LOCAL',
    EQUIVISI INTEGER NOT NULL COMMENT 'CODIGO INTERNO DEL EQUIPO VISITANTE',
    GOLLOC INTEGER NOT NULL COMMENT 'GOLES MARCADOS POR EL EQUIPO LOCAL',
    GOLVISI INTEGER NOT NULL COMMENT 'GOLES MARCADOS POR EL EQUIPO VISITANTE',
    FALTALOC INTEGER NOT NULL COMMENT 'FALTAS DEL EQUIPO LOCAL',
    FALTAVISI INTEGER NOT NULL COMMENT 'FALTAS DEL EQUIPO VISITANTE',
    
    CONSTRAINT REL_CODEQ FOREIGN KEY (CODEQ) REFERENCES EQUIPO (CODEQ),
    CONSTRAINT REL_CODJU FOREIGN KEY (CODJU) REFERENCES JUGADORES (CODJU)
);