CREATE DATABASE MONOLOGOS;
USE MONOLOGOS;

CREATE TABLE IF NOT EXISTS MONOLOGOS(
	IDMON INTEGER AUTO_INCREMENT COMMENT 'IDNENTIFICADOR DEL MONOLOGO', 
    TIT VARCHAR(100) COMMENT 'TITULO DEL MONOLOGO',
    TIP SET('DRAMATICO','COMICO','INTERIOR') NOT NULL COMMENT 'TIPO DE MONOLOGO',
    CAR VARCHAR(800) COMMENT 'LINK DE LA IMAGEN DEL CARTEL PARA EL ESPECTACULO',
    HUM VARCHAR(60) NOT NULL COMMENT 'NOMBRE DEL HUMORISTA',
    FEAT DATETIME NOT NULL COMMENT 'FECHA DE LA ACTUACIÓN',
    TEAT VARCHAR(100) NOT NULL COMMENT 'TEATRO DONDE SE CELEBRA EL MONOLOGO',
    PENT DOUBLE NOT NULL COMMENT 'PRECIO DE LA ENTRADA',
    DURTOT INTEGER COMMENT 'DURACION TOTAL DEL ESPECTACULO',
    PRIMARY KEY ID_MONOLOGO (IDMON),
    KEY TITULO (TIT),
    KEY HUMORISTA (HUM),
    KEY TEATRO (TEAT),
    KEY FECHA_ACTUACION (FEAT)
);

CREATE TABLE IF NOT EXISTS CHISTES(
	IDCH INTEGER PRIMARY KEY AUTO_INCREMENT COMMENT 'IDENTIFICADOR DEL CHISTE',
    TIT VARCHAR(200) NOT NULL COMMENT 'TITULO DEL CHISTE',
    TEM VARCHAR(20) COMMENT 'TEMATICA',
    TIP ENUM('HUMOR NEGRO','HUMOR BLANCO','VERDUSCO','EXAGERACIÓN','IRÓNICO','INCONGRUENTE','CLÁSICO','TELÓN','GRAFICO','PERSONAJES','INTELIGENTES','ANIMALES','ESTEREOTIPOS') NOT NULL COMMENT 'TIPO DE CHISTE',
    CHI LONGTEXT NOT NULL COMMENT 'EL CHISTE',
    DURMIN INTEGER NOT NULL COMMENT 'DURACION DEL CHISTE EN MINUTOS',
    NOTA INTEGER COMMENT 'NOTA DEL CHISTE DE 0 A 10'
);

CREATE TABLE IF NOT EXISTS ASIGNA(
	IDMON INTEGER NOT NULL COMMENT 'IDENTIFICADOR DEL MONOLOGO (TABLA MONOLOGOS)',
    IDCHI INTEGER NOT NULL COMMENT 'IDENTIFICADOR DEL CHISTE (TABLA CHISTES)',
    FEALT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'FECHA Y HORA DE ALTA DEL CHISTE',
    FEASG TIMESTAMP NOT NULL COMMENT 'FECHA Y HORA DE ASIGNACION DEL CHISTE',
    FEBAJ TIMESTAMP NOT NULL COMMENT 'FECHA Y HORA DE BAJA DEL CHISTE (CUANDO UN CHISTE SE DESASIGNA DEL MONOLOGO)',
    ORDEN INTEGER NOT NULL COMMENT 'POSICIÓN QUE OCUPA DENTRO DEL MONOLOGO',
    CONSTRAINT RELACION_MONOLOGO FOREIGN KEY (IDMON) REFERENCES MONOLOGOS (IDMON),
    CONSTRAINT RELACION_CHISTE FOREIGN KEY (IDCHI) REFERENCES CHISTES (IDCH)
);