CREATE DATABASE FORMACIONPROF;
USE FORMACIONPROF;

CREATE TABLE IF NOT EXISTS ALUMNOS(
	CODIGO INTEGER PRIMARY KEY AUTO_INCREMENT COMMENT 'CODIGO INTERNO DEL ALUMNO',
    NOMBRE VARCHAR(200) NOT NULL COMMENT 'NOMBRE DEL ALUMNO',
    EDAD INTEGER NOT NULL COMMENT 'EDAD DEL ALUMNO',
    TLF VARCHAR(14) NOT NULL COMMENT 'TELEFONO DEL ALUMNO',
    NIF VARCHAR(12) COMMENT 'DNI DEL ALUMNO',
    CP VARCHAR(5) COMMENT 'CODIGO POSTAL DEL DOMICILIO DEL ALUMNO',
    NIVEL_ESTPREV INTEGER COMMENT 'NIVEL DE ESTUDIOS PREVIOS DEL ALUMNO',
    FOREIGN KEY (NIVEL_ESTPREV) REFERENCES ESTUDIOS_PREVIOS(COD)
);

CREATE TABLE IF NOT EXISTS ESTUDIOS_PREVIOS (
	COD INTEGER PRIMARY KEY AUTO_INCREMENT COMMENT 'CODIGO INTERNO DE LOS ESTUDIOS PREVIOS',
    DENOMINACION VARCHAR(100) NOT NULL COMMENT 'DENOMINACIÓN DE LOS ESTUDIOS PREVIOS',
    FAMILIA VARCHAR(200) COMMENT 'FAMILIA DE LOS ESTUDIOS PREVIOS',
    NIVEL VARCHAR(100) NOT NULL COMMENT 'NIVEL DE LOS ESTUDIOS PREVIOS'
);

CREATE TABLE IF NOT EXISTS MODULOS (
	CODIGO INTEGER PRIMARY KEY AUTO_INCREMENT COMMENT 'CODIGO INTENRO DEL MODULO',
    DESCRIPCION VARCHAR(200) NOT NULL COMMENT 'DESCRIPCION DEL MODULO',
    HORAS INTEGER NOT NULL COMMENT 'HORAS DEL MODULO',
    RAMA VARCHAR(200) NOT NULL COMMENT 'RAMA A LA QUE PERTENCE MODULO',
    CURSO INTEGER NOT NULL COMMENT 'CURSO AL QUE APLICA EL MODULO'
);

CREATE TABLE IF NOT EXISTS MATRICULA (
	CODALU INTEGER NOT NULL COMMENT 'CODIGO DEL ALUMNO',
	CODMODU INTEGER NOT NULL COMMENT 'CODIGO DEL MODULO',
    FECHAINI DATE NOT NULL COMMENT 'FECHA DE INICIO DE LA MATRUCLA',
    FECHAFIN DATE COMMENT 'FECHA DE FIN DE LA MATRUCLA',
    NOTA1T DOUBLE COMMENT 'NOTA DEL PRIMER TRIMESTRE',
    NOTA2T DOUBLE COMMENT 'NOTA DEL SEGUNDO TRIMESTRE',
    NOTA3T DOUBLE COMMENT 'NOTA DEL TERCER TRIMESTRE',
    FOREIGN KEY (CODALU) REFERENCES ALUMNOS(CODIGO),
    FOREIGN KEY (CODMODU) REFERENCES MODULOS(CODIGO)
);


INSERT INTO ALUMNOS (NOMBRE, EDAD, TLF, NIF, CP, NIVEL_ESTPREV) VALUES ('PEDRO', 19, '+346487586', '45789654Z', '28903', 2);
INSERT INTO ALUMNOS (NOMBRE, EDAD, TLF, NIF, CP, NIVEL_ESTPREV) VALUES ('ANA', 21, '+346567898', '11455767L', '09430', 1);
INSERT INTO ALUMNOS (NOMBRE, EDAD, TLF, NIF, NIVEL_ESTPREV) VALUES ('LUCIA', 18, '+344647885', '52505013S', 2);

INSERT INTO MODULOS (DESCRIPCION, HORAS, RAMA, CURSO) VALUES ('BASES DE DATOS', 205, 'GESTIÓN INFORMACIÓN', '1');
INSERT INTO MODULOS (DESCRIPCION, HORAS, RAMA, CURSO) VALUES ('PROGRAMACIÓN', 240, 'DESARROLLO APLICACIONES', '1');
INSERT INTO MODULOS (DESCRIPCION, HORAS, RAMA, CURSO) VALUES ('SISTEMAS INFORMÁTICOS', 85, 'GESTIÓN INFORMACIÓN', '1');

INSERT INTO MATRICULA (CODALU, CODMODU, FECHAINI, NOTA1T, NOTA2T, NOTA3T) VALUES (1, 3, '2021-09-21', 5.5, 6.2, 7.8);
INSERT INTO MATRICULA (CODALU, CODMODU, FECHAINI, NOTA1T, NOTA2T, NOTA3T) VALUES (2, 2, '2020-03-15', 7.4, 4.5, 8.0);
INSERT INTO MATRICULA (CODALU, CODMODU, FECHAINI, NOTA1T, NOTA2T, NOTA3T) VALUES (3, 1, '2021-06-22', 8.0, 9.0, 10.0);

INSERT INTO ESTUDIOS_PREVIOS (DENOMINACION, FAMILIA, NIVEL) VALUES ('BACHILLERATO CIENCIAS', 'CIENCIA Y TECNOLOGIA', 'MEDIO');
INSERT INTO ESTUDIOS_PREVIOS (DENOMINACION, FAMILIA, NIVEL) VALUES ('DAM', 'TIC', 'MEDIO');
INSERT INTO ESTUDIOS_PREVIOS (DENOMINACION, FAMILIA, NIVEL) VALUES ('DAM', 'TIC', 'SUPERIOR');

SELECT *, ((NOTA1T + NOTA2T + NOTA3T)/3) AS MEDIA_GLOBAL FROM MATRICULA;

CREATE TABLE IF NOT EXISTS RESPALDO LIKE MATRICULA;
ALTER TABLE RESPALDO ADD MEDIA_GLOBAL DOUBLE COMMENT 'MEDIA ARITMETICA DE LAS TODAS DE LOS TRES TRIMESTRES';
INSERT INTO RESPALDO SELECT *, ((NOTA1T + NOTA2T + NOTA3T)/3) AS MEDIA_GLOBAL FROM MATRICULA;

SELECT TLF FROM ALUMNOS WHERE EDAD < 20;

DELETE FROM MATRICULA WHERE CODALU = 3;