CREATE DATABASE TIENDA;
USE TIENDA;

CREATE TABLE IF NOT EXISTS CLIENTES(
	COD INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOM VARCHAR(100),
    EDAD INTEGER
);

CREATE TABLE IF NOT EXISTS PRODUCTOS(
	CODF INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS FACTURAS(
	COD INTEGER,
	CODF INTEGER,
    CANT INTEGER,
    FOREIGN KEY (COD) REFERENCES CLIENTES(COD),
    FOREIGN KEY (CODF) REFERENCES PRODUCTOS(CODF)
);

INSERT INTO CLIENTES (NOM) VALUES ('PEPE');
INSERT INTO CLIENTES (NOM) VALUES ('PEPA');
INSERT INTO CLIENTES (NOM) VALUES ('PEPO');
INSERT INTO CLIENTES (NOM) VALUES ('PIPO');

INSERT INTO PRODUCTOS (NOMBRE) VALUES ('PERA');
INSERT INTO PRODUCTOS (NOMBRE) VALUES ('PEPINO');
INSERT INTO PRODUCTOS (NOMBRE) VALUES ('PARANGON');
INSERT INTO PRODUCTOS (NOMBRE) VALUES ('PLATANO');

INSERT INTO FACTURAS (COD, CODF, CANT) VALUES (1, 2, 1);
INSERT INTO FACTURAS (COD, CODF, CANT) VALUES (1, 3, 4);
INSERT INTO FACTURAS (COD, CODF, CANT) VALUES (2, 4, 3);
INSERT INTO FACTURAS (COD, CODF, CANT) VALUES (3, 2, 2);
INSERT INTO FACTURAS (COD, CODF, CANT) VALUES (3, 1, 6);

SELECT * FROM CLIENTES INNER JOIN PRODUCTOS ON COD = CODF;
SELECT * FROM CLIENTES LEFT JOIN PRODUCTOS ON COD = CODF;
SELECT * FROM CLIENTES RIGHT JOIN PRODUCTOS ON COD = CODF;

SELECT * FROM CLIENTES NATURAL JOIN PRODUCTOS;
SELECT * FROM CLIENTES FULL JOIN PRODUCTOS;