CREATE DATABASE FORMACION;
USE FORMACION;

CREATE TABLE ALUMNOS(
	COD INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    APELLIDOS VARCHAR(100),
    FNACI DATE,
    NOTA1 DOUBLE,
    NOTA2 DOUBLE,
    FINAL DOUBLE,
    CEXP VARCHAR(15)
);

INSERT INTO ALUMNOS (NOMBRE,APELLIDOS,FNACI,NOTA1,NOTA2) VALUES 
('ANDREA','ALISEDA','2002-11-01',7.5,8.0),
('ANDRES','ALVAREZ','2000-03-01',6.5,4.0),
('ATANASIO','ALVAREZ','1998-10-01',8.5,3.0),
('ALBERTA','ALVAREZ','2010-12-01',5.5,7.0);

SELECT  * FROM ALUMNOS;
SELECT * FROM ACTAS;

CREATE TABLE ACTAS (
	CODIGO INTEGER,
    APELNOM CHAR(100),
    NOTA DOUBLE,
    CODEXP  CHAR(15)
);

SELECT NOTA_EXPEDIENTE(7.0,8.5);

CALL FORMACION.ACTUALIZA_ACTAS;

TRUNCATE ACTAS;

/* ----------------------------------------------- */





CREATE DEFINER=`root`@`localhost` FUNCTION `NOTA_EXPEDIENTE`(NOTA1 DOUBLE,NOTA2 DOUBLE) RETURNS char(15) CHARSET utf8mb4
BEGIN
	DECLARE NOTAFINAL CHAR(15);
    DECLARE MEDIA DOUBLE;
    
    SET MEDIA = (NOTA1 + NOTA2)/2;
    
    IF MEDIA<5 THEN
		SET NOTAFINAL = "SUSPENSO";
    ELSEIF MEDIA<7 THEN
		SET NOTAFINAL = "APROBADO";
    ELSEIF MEDIA<9 THEN
		SET NOTAFINAL = "NOTABLE";
    ELSEIF MEDIA<=10 THEN
		SET NOTAFINAL = "SOBRESALIENTE";
    ELSE
		SET NOTAFINAL = "NOTA NO VALIADA";    
    END IF;

RETURN NOTAFINAL;
END

/* --------------------------------------------------------- */

CREATE DEFINER=`root`@`localhost` PROCEDURE `ACTUALIZA_ACTAS`()
BEGIN
	DECLARE CONTADOR INTEGER;
    DECLARE REG INTEGER;
    DECLARE NOTALETRA VARCHAR(15);
    DECLARE CODIG INTEGER;
    DECLARE NOTAMED DOUBLE;
    DECLARE APELNOMBRE VARCHAR(100);
   
    SET CONTADOR = 1;
    SET REG = (SELECT MAX(COD) FROM ALUMNOS);
    WHILE CONTADOR <= REG DO
		SET NOTALETRA = (SELECT NOTA_EXPEDIENTE(NOTA1,NOTA2) FROM ALUMNOS WHERE COD=CONTADOR);
		SET CODIG = (SELECT COD FROM ALUMNOS WHERE COD=CONTADOR);
		SET APELNOMBRE = (SELECT CONCAT(APELLIDOS,', ',NOMBRE) FROM ALUMNOS WHERE COD=CONTADOR);
        SET NOTAMED = (SELECT (NOTA1+NOTA2)/2 FROM ALUMNOS WHERE COD=CONTADOR);
        
        UPDATE ALUMNOS SET FINAL= NOTAMED, CEXP = NOTALETRA WHERE COD = CONTADOR;

        IF  (NOTALETRA = "NOTABLE" OR NOTALETRA = "SOBRESALIENTE") THEN
			INSERT INTO ACTAS VALUES (CODIG,APELNOMBRE,NOTAMED,NOTALETRA);
        END IF;
        
		SET CONTADOR = CONTADOR + 1;
    END WHILE;
END

/* --------------------------------------------------- */

