SELECT * FROM red.usuarios;
SELECT * FROM red.actas;
select * from red.log;

INSERT INTO usuarios (CP,NOMBRE,APE1,FNACI,NOTA1,NOTA2) VALUES 
(4899,'ANDREA','ALISEDA','2002-11-01',7.5,8.0),
(5933,'ANDRES','ALVAREZ','2000-03-01',6.5,4.0),
(6944,'ATANASIO','ALVAREZ','1998-10-01',8.5,3.0),
(7833,'ALBERTA','ALVAREZ','2010-12-01',5.5,7.0);

SELECT NOTA_EXPEDIENTE(7.0,8.5);
CALL ACTUALIZA_ACTAS;

CREATE TABLE LOG (
	CP INT,
    NOMBRE CHAR(50),
    NOTA DOUBLE,
    CALIF CHAR(50)
);

DELIMITER //
CREATE TRIGGER COPIA AFTER DELETE ON USUARIOS FOR EACH ROW BEGIN
	INSERT INTO LOG SET LOG.CP = OLD.CP,
						LOG.NOMBRE = OLD.NOMBRE,
                        LOG.NOTA = OLD.FINAL,
                        LOG.CALIF = OLD.CEXP,
                        LOG.USUARIO = OLD.USUARIO,
                        LOG.FECHA = OLD.FNACI;
END//
// DELIMITER ;

DELETE FROM USUARIOS;

SHOW TRIGGERS;
DROP TRIGGER COPIA;