CREATE DATABASE LIBRERIA;
USE LIBRERIA;

CREATE TABLE IF NOT EXISTS CLIENTES(
	NIF VARCHAR(12) COMMENT 'DNI',
    NOMBRE VARCHAR(60) NOT NULL COMMENT 'APELLIDOS Y NOMBRE',
	SEXO ENUM('HOMBRE','MUJER'),
    EMAIL VARCHAR(60) NOT NULL COMMENT 'CORREO ELECTRONICO',
    TEL VARCHAR(14) COMMENT 'TELEFONO',
    EDAD INTEGER,
    FECHNACI DATE COMMENT 'FECHEA NDE NACIMIENTO',
    PRIMARY KEY (NIF),
    UNIQUE KEY (TEL),
    KEY (NOMBRE)
);

CREATE TABLE IF NOT EXISTS LIBROS(
	ISBN VARCHAR(20) NOT NULL,
    TIT VARCHAR(100) NOT NULL COMMENT 'TITULO',
    AUT VARCHAR(30) COMMENT 'AUTOR',
    PRIMARY KEY (ISBN, AUT)
);

DESCRIBE LIBROS;
DESCRIBE CLIENTES;

CREATE TABLE IF NOT EXISTS COMPRAS(
	NIFCLI VARCHAR(12) NOT NULL,
    ISBN VARCHAR(50) NOT NULL,
    IDCO INTEGER AUTO_INCREMENT UNIQUE KEY,
	FCOMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    TOTPRE DOUBLE,
    CONSTRAINT COMPRAS_CLIENTES FOREIGN KEY (NIFCLI) REFERENCES CLIENTES (NIF) ON DELETE CASCADE,
    CONSTRAINT COMPRAS_LIBROS FOREIGN KEY (ISBN) REFERENCES LIBROS (ISBN, AUTOR)
);